# Generated by Django 3.1.1 on 2020-09-28 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200927_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='listing_id',
            new_name='listing',
        ),
    ]
